version: '3'
services:
    jenkins:
        image: jenkins:2.60.3
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "29000:8080"
          - "50000:50000"
        environment:
          - CLIENTPORT=8080
        volumes:
          - "./jenkins_home:/var/jenkins_home"